name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        id: deps
        run: nci

      - name: Lint
        if: steps.deps.outcome == 'success'
        run: nr lint

      - name: Typecheck
        if: steps.deps.outcome == 'success'
        run: nr typecheck
